# pacserve configuration file

# Service name to announce, defaults to the local hostname
#SERVICE=

# Distribution to announce, defaults to ID of os-release
#DIST=

# Architecture to announce, defaults to `uname -m`
#ARCH=

# Port to listen on
#PORT=7078
