#!/bin/sh

build() {
	add_runscript
}

help() {
	echo 'This hook adds peers to pacredir.conf from inside initramfs.'
	echo 'Useless for installed systems, but can be handy with'
	echo 'no-persistent configurations.'
}
