#!/bin/sh

run_latehook() {
	local newroot="/new_root/"

	if ! grep -q '^pacserve hosts' ${newroot}/etc/pacredir.conf; then
		case $(uname -m) in
			x86_64)
				if [[ -n "${pacserve_x86_64}" ]]; then
					msg ":: Adding pacserve host '${pacserve_x86_64}' to pacredir.conf..."
					echo "pacserve hosts = ${pacserve_x86_64}" >> ${newroot}/etc/pacredir.conf
				fi
				;;
			i686)
				if [[ -n "${pacserve_i686}" ]]; then
					msg ":: Adding pacserve host '${pacserve_i686}' to pacredir.conf..."
					echo "pacserve hosts = ${pacserve_i686}" >> ${newroot}/etc/pacredir.conf
				fi
				;;
		esac
	fi
}
