#!/bin/sh
 
case "${reason}" in
	BOUND|REBIND|REBOOT|RENEW|TIMEOUT|STATIC)
		# inform pacredir about reestablished connection
		kill -HUP $(pgrep pacredir)
		;;
	PREINIT|EXPIRE|INFORM|FAIL|IPV4LL|NAK|NOCARRIER|RELEASE|STOP)
		# do nothing here...
		;;
esac
